# Generated by Django 6.0.4 on 2026-05-04 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huit_username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Tài khoản HUIT liên kết')),
                ('huit_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email HUIT')),
                ('is_linked', models.BooleanField(default=False, verbose_name='Đã liên kết với HUIT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
