"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0x=ef3hz-1)yv+-c#*^pkzsqejmg!x)nf*d%fdz!_xjhfu-!@d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []

# Cho phép ngrok
ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev'
]

CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
 # -----------------------


# Application definition

INSTALLED_APPS = [
    'jazzmin', # Thêm jazzmin vào INSTALLED_APPS
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "accounts", #  Ứng dụng quản lý người dùng
]
# Giao diện tùy chỉnh cho Jazzmin 
JAZZMIN_UI_CONFIG = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "topmenu_links": [
        {"name": "Trang chủ", "url": "admin:index"},
        {"name": "Dashboard Tự Chế", "url": "/admin-dashboard/"},
        # NÚT QUAY LẠI HUYỀN THOẠI ĐÂY:
        {"name": "Giao diện Trắng Xanh", "url": "/admin-origin/"}, 
    ],
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'accounts.middleware.RoleMiddleware',

    'accounts.middleware.ForceDisable2FAMiddleware',
    'accounts.middleware.ForceLogoutMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    
    
    'accounts.middleware.UpdateDeviceMiddleware',
    
   
]

ROOT_URLCONF = 'huit_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
        'DIRS': [BASE_DIR / 'templates'],  # Đường dẫn đến thư mục templates
    },
]

WSGI_APPLICATION = 'huit_project.wsgi.application' 
# giữ tên cũ để tương thích với get_wsgi_application() trong basehttp.py
ASGI_APPLICATION = 'huit_project.asgi.application'
# giữ tên cũ để tương thích với get_wsgi_application() trong basehttp.py, dù chúng ta không dùng ASGI ở đây.

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Thêm dòng này để gom file tĩnh khi deploy lên Azure/Render
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Cấu hình Media (Nếu bạn muốn User upload ảnh đại diện)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cấu hình Login/Logout
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

# settings.py



# Cấu hình Gmail 
'''EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tuankiet5274@gmail.com' # Email gửi email
EMAIL_HOST_PASSWORD = 'aqgu lwlm askj clnt' # pass email (cần tạo app password nếu dùng Gmail)'''
# Drive015
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'kiethtt@drive015.com' # Email gửi email
EMAIL_HOST_PASSWORD = 'vqrx dfnb zyko zubz'



#mail icloud
'''EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.me.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#
EMAIL_HOST_USER = 'kiethtt@icloud.com' # Email gửi email
EMAIL_HOST_PASSWORD = 'aejx-dcfq-edjc-yibq' # pass email (cần tạo app password nếu dùng iCloud)
#
#SỬA LỖI 550 5.7.0 "Relaying denied" 
DEFAULT_FROM_EMAIL = 'kiethtt@icloud.com' '''
#FIDO2
# Cho phép session lưu các object phức tạp 

#SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
