# Generated by Django 6.0.3 on 2026-05-15 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('temp_data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Đăng ký tạm chờ xác thực',
                'verbose_name_plural': 'Đăng ký tạm chờ xác thực',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempt', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tên đăng nhập thử')),
                ('action', models.CharField(choices=[('login', 'Đăng nhập thành công'), ('logout', 'Đăng xuất'), ('login_failed', 'Đăng nhập thất bại'), ('login_locked_attempt', 'Đăng nhập tài khoản bị khóa'), ('force_logout', 'Admin cưỡng chế đăng xuất'), ('otp_fail', 'Xác thực OTP thất bại'), ('otp_success', 'Xác thực OTP thành công'), ('2fa_enable', 'Bật bảo mật 2FA'), ('2fa_disable', 'Tắt bảo mật 2FA'), ('register', 'Đăng ký tài khoản')], max_length=30, verbose_name='Hành động')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Nhật ký hoạt động',
                'verbose_name_plural': 'Nhật ký hoạt động',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(blank=True, default='', max_length=6, verbose_name='OTP plaintext (bị xóa sau hash)')),
                ('otp_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='SHA-256 hash của OTP')),
                ('action', models.CharField(choices=[('register', 'Đăng ký tài khoản'), ('login_2fa', 'Đăng nhập 2FA'), ('setup_2fa', 'Thiết lập Email 2FA'), ('update_info', 'Cập nhật thông tin'), ('disable_2fa', 'Tắt Email 2FA')], default='login_2fa', max_length=20, verbose_name='Loại thao tác')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Địa chỉ IP')),
                ('email_sent', models.CharField(blank=True, max_length=254, null=True, verbose_name='Email đích')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm sử dụng')),
                ('is_used', models.BooleanField(default=False, verbose_name='Đã sử dụng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiệu lực')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Email OTP Log',
                'verbose_name_plural': 'Email OTP Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemoteAuthRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('device_info', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('approved', 'Đã đồng ý'), ('denied', 'Đã từ chối')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu xác thực từ xa',
                'verbose_name_plural': 'Yêu cầu xác thực từ xa',
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(default='Thiết bị không xác định', max_length=255)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thiết bị tin cậy',
                'verbose_name_plural': 'Thiết bị tin cậy',
            },
        ),
        migrations.CreateModel(
            name='UserPasskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(max_length=500, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passkey (FIDO2)',
                'verbose_name_plural': 'Passkeys (FIDO2)',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Chữ đệm')),
                ('phone_number', models.CharField(blank=True, default='', max_length=15, verbose_name='Số điện thoại')),
                ('otp_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('hotp_counter', models.PositiveBigIntegerField(default=0, verbose_name='HOTP Counter')),
                ('has_app_otp', models.BooleanField(default=False, verbose_name='Đã bật App OTP (TOTP)')),
                ('has_email_otp', models.BooleanField(default=False, verbose_name='Đã bật Email OTP')),
                ('has_hotp', models.BooleanField(default=False, verbose_name='Đã bật HOTP')),
                ('force_disable_2fa', models.BooleanField(default=False, verbose_name='Admin tắt buộc 2FA')),
                ('is_required', models.BooleanField(default=False, verbose_name='Bắt buộc bật 2FA')),
                ('force_logout', models.BooleanField(default=False, verbose_name='Cưỡng chế đăng xuất')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
            },
        ),
    ]
