# Generated by Django 6.0.3 on 2026-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_push_auth',
            field=models.BooleanField(default=True, verbose_name='Cho phép xác nhận đăng nhập từ thiết bị khác'),
        ),
    ]
