# Generated by Django 6.0.3 on 2026-05-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_allow_push_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteauthrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp_code',
            field=models.CharField(max_length=64),
        ),
    ]
