# Generated by Django 6.0.3 on 2026-04-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_activitylog_options_activitylog_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fido2_credential',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_fido2',
            field=models.BooleanField(default=False, verbose_name='Đã bật FIDO2'),
        ),
    ]
