# Generated by Django 6.0.3 on 2026-05-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remoteauthrequest_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Đăng nhập thành công'), ('logout', 'Đăng xuất'), ('login_failed', 'Đăng nhập thất bại'), ('login_locked_attempt', 'Đăng nhập tài khoản bị khóa'), ('force_logout', 'Admin cưỡng chế đăng xuất'), ('otp_fail', 'Xác thực OTP thất bại'), ('otp_success', 'Xác thực OTP thành công'), ('2fa_enable', 'Bật bảo mật 2FA'), ('2fa_disable', 'Tắt bảo mật 2FA'), ('register', 'Đăng ký tài khoản'), ('account_toggle', 'Admin khóa / mở khóa tài khoản')], max_length=30, verbose_name='Hành động'),
        ),
    ]
