# Generated by Django 6.0.3 on 2026-05-16 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_activitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=50)),
                ('action', models.CharField(default='login_2fa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'OTP Attempt (Rate Limit)',
                'verbose_name_plural': 'OTP Attempts (Rate Limit)',
            },
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'action', 'is_used', 'is_active'], name='emailotp_verify_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email_sent', 'action', 'is_active'], name='emailotp_pending_idx'),
        ),
        migrations.AddField(
            model_name='otpattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otpattempt',
            index=models.Index(fields=['user', 'action', 'created_at'], name='otpattempt_user_idx'),
        ),
        migrations.AddIndex(
            model_name='otpattempt',
            index=models.Index(fields=['ip_address', 'action', 'created_at'], name='otpattempt_ip_idx'),
        ),
    ]
