# Generated by Django 6.0.3 on 2026-05-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otpattempt_emailotp_emailotp_verify_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hotp_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HOTP Secret (encrypted)'),
        ),
    ]
