# Generated by Django 6.0.3 on 2026-05-16 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_hotp_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteauthrequest',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TOTP Secret (encrypted)'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='actlog_user_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'timestamp'], name='actlog_action_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['ip_address', 'action'], name='actlog_ip_action_idx'),
        ),
        migrations.AddIndex(
            model_name='remoteauthrequest',
            index=models.Index(fields=['session_key', 'expires_at'], name='remoteauth_session_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'is_active'], name='trusteddev_user_active_idx'),
        ),
    ]
