# Generated by Django 6.0.3 on 2026-05-19 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_remoteauthrequest_session_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trusteddevice',
            name='is_trusted',
            field=models.BooleanField(default=False, help_text='Thiết bị này có thể nhận và xử lý yêu cầu xác nhận đăng nhập từ thiết bị khác.', verbose_name='Thiết bị tin cậy (nhận thông báo xác nhận)'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'is_active', 'is_trusted'], name='trusteddev_trusted_idx'),
        ),
    ]
