# Generated by Django 6.0.3 on 2026-04-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user2fa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2fa',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Bắt buộc xác thực 2FA'),
        ),
    ]
