# Generated by Django 6.0.3 on 2026-05-19 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_backupcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteauthrequest',
            name='target_device_session',
            field=models.CharField(blank=True, default='', help_text='Session key của trusted device được chọn để xác nhận yêu cầu này.', max_length=40, verbose_name='Session của thiết bị nhận push'),
        ),
        migrations.AddIndex(
            model_name='remoteauthrequest',
            index=models.Index(fields=['target_device_session', 'status'], name='remoteauth_target_status_idx'),
        ),
    ]
