# Generated by Django 6.0.3 on 2026-05-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remoteauthrequest_target_device_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOTPAttempt',
            fields=[
            ],
            options={
                'verbose_name': 'HOTP Attempt (Rate Limit)',
                'verbose_name_plural': 'HOTP Attempts (Rate Limit)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.otpattempt',),
        ),
    ]
