# Generated by Django 6.0.3 on 2026-05-04 20:46

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp_secret',
            field=models.CharField(blank=True, default=pyotp.random_base32, max_length=32),
        ),
    ]
