# Generated by Django 6.0.3 on 2026-05-21 05:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_hotpattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('detail', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('level', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('danger', 'Khẩn cấp')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_enabled', models.BooleanField(default=True, verbose_name='Cho phép đăng ký mới')),
                ('require_2fa_all', models.BooleanField(default=False, verbose_name='Bắt buộc 2FA cho tất cả user')),
                ('otp_expiry_minutes', models.PositiveIntegerField(default=5, verbose_name='Thời hạn OTP (phút)')),
                ('otp_max_retry', models.PositiveIntegerField(default=5, verbose_name='Số lần retry OTP tối đa')),
                ('session_timeout_hours', models.PositiveIntegerField(default=24, verbose_name='Timeout phiên (giờ)')),
                ('ip_whitelist', models.TextField(blank=True, default='', verbose_name='IP Whitelist')),
                ('ip_blacklist', models.TextField(blank=True, default='', verbose_name='IP Blacklist')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cài đặt hệ thống',
                'verbose_name_plural': 'Cài đặt hệ thống',
            },
        ),
    ]
