# Generated by Django 6.0.3 on 2026-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_adminauditlog_announcement_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_2fa_setup_done',
            field=models.BooleanField(default=False),
        ),
    ]
