# Generated by Django 6.0.3 on 2026-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_emailotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
