# Generated by Django 6.0.3 on 2026-05-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_admin_2fa_setup_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='otp_plain_demo',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='OTP gốc (demo)'),
        ),
    ]
