# Generated by Django 6.0.3 on 2026-05-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_userprofile_otp_secret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
