# Generated by Django 6.0.3 on 2026-05-08 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email OTP Log'},
        ),
        migrations.AddField(
            model_name='emailotp',
            name='action',
            field=models.CharField(choices=[('register', 'Đăng ký tài khoản'), ('login_2fa', 'Đăng nhập 2FA'), ('setup_2fa', 'Thiết lập Email 2FA'), ('update_info', 'Cập nhật thông tin'), ('disable_2fa', 'Tắt Email 2FA')], default='login_2fa', max_length=20, verbose_name='Loại thao tác'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='email_sent',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Email đích'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Địa chỉ IP'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hiệu lực'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm OTP được sử dụng'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('login_failed', 'Đăng nhập thất bại'), ('login_locked_attempt', 'Đăng nhập tài khoản bị khoá'), ('force_logout', 'Cưỡng chế đăng xuất'), ('otp_fail', 'Xác thực OTP thất bại'), ('otp_success', 'Xác thực OTP thành công'), ('2fa_enable', 'Bật bảo mật 2FA'), ('2fa_disable', 'Tắt bảo mật 2FA'), ('register', 'Đăng ký tài khoản')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Mã OTP đã băm SHA-256'),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
