# Generated by Django 6.0.3 on 2026-05-13 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_emailotp_options_emailotp_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Nhật ký hoạt động'},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'verbose_name': 'Lịch sử đăng nhập', 'verbose_name_plural': 'Lịch sử đăng nhập'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': '[DEPRECATED] OTP cũ'},
        ),
        migrations.AlterModelOptions(
            name='pendingregistration',
            options={'verbose_name': 'Đăng ký tạm chờ xác thực'},
        ),
        migrations.AlterModelOptions(
            name='remoteauthrequest',
            options={'verbose_name': 'Yêu cầu xác thực từ xa'},
        ),
        migrations.AlterModelOptions(
            name='trusteddevice',
            options={'verbose_name': 'Thiết bị tin cậy'},
        ),
        migrations.AlterModelOptions(
            name='user2fa',
            options={'verbose_name': 'Cấu hình 2FA (Admin)'},
        ),
        migrations.AlterModelOptions(
            name='userpasskey',
            options={'verbose_name': 'Passkey (FIDO2)'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Hồ sơ người dùng'},
        ),
        migrations.AlterModelOptions(
            name='usersessioncontrol',
            options={'verbose_name': 'Kiểm soát phiên người dùng'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('login_failed', 'Đăng nhập thất bại'), ('login_locked_attempt', 'Đăng nhập tài khoản bị khoá'), ('force_logout', 'Cưỡng chế đăng xuất'), ('otp_fail', 'Xác thực OTP thất bại'), ('otp_success', 'Xác thực OTP thành công'), ('2fa_enable', 'Bật bảo mật 2FA'), ('2fa_disable', 'Tắt bảo mật 2FA'), ('register', 'Đăng ký tài khoản')], max_length=30, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Địa chỉ IP'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='username_attempt',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tên đăng nhập thử'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Đã sử dụng'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp_code',
            field=models.CharField(max_length=6, verbose_name='Mã OTP (plaintext - DEMO)'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm sử dụng'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='user2fa',
            name='email_otp_enabled',
            field=models.BooleanField(default=False, verbose_name='Bật Email OTP'),
        ),
        migrations.AlterField(
            model_name='user2fa',
            name='force_disable_2fa',
            field=models.BooleanField(default=False, verbose_name='Admin tắt buộc 2FA'),
        ),
        migrations.AlterField(
            model_name='user2fa',
            name='google_auth_enabled',
            field=models.BooleanField(default=False, verbose_name='Bật Google Auth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_app_otp',
            field=models.BooleanField(default=False, verbose_name='Đã bật App OTP'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_email_otp',
            field=models.BooleanField(default=False, verbose_name='Đã bật Email OTP'),
        ),
        migrations.AlterField(
            model_name='usersessioncontrol',
            name='force_logout',
            field=models.BooleanField(default=False, verbose_name='Cưỡng chế đăng xuất'),
        ),
    ]
