# Generated by Django 6.0.3 on 2026-05-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_activitylog_options_alter_loginhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user2fa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersessioncontrol',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Nhật ký hoạt động', 'verbose_name_plural': 'Nhật ký hoạt động'},
        ),
        migrations.AlterModelOptions(
            name='emailotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email OTP Log', 'verbose_name_plural': 'Email OTP Logs'},
        ),
        migrations.AlterModelOptions(
            name='pendingregistration',
            options={'verbose_name': 'Đăng ký tạm chờ xác thực', 'verbose_name_plural': 'Đăng ký tạm chờ xác thực'},
        ),
        migrations.AlterModelOptions(
            name='remoteauthrequest',
            options={'verbose_name': 'Yêu cầu xác thực từ xa', 'verbose_name_plural': 'Yêu cầu xác thực từ xa'},
        ),
        migrations.AlterModelOptions(
            name='trusteddevice',
            options={'verbose_name': 'Thiết bị tin cậy', 'verbose_name_plural': 'Thiết bị tin cậy'},
        ),
        migrations.AlterModelOptions(
            name='userpasskey',
            options={'verbose_name': 'Passkey (FIDO2)', 'verbose_name_plural': 'Passkeys (FIDO2)'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_otp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fido2_credential',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_fido2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_expiry',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='force_disable_2fa',
            field=models.BooleanField(default=False, verbose_name='Admin tắt buộc 2FA'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='force_logout',
            field=models.BooleanField(default=False, verbose_name='Cưỡng chế đăng xuất'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Bắt buộc bật 2FA'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Đăng nhập thành công'), ('logout', 'Đăng xuất'), ('login_failed', 'Đăng nhập thất bại'), ('login_locked_attempt', 'Đăng nhập tài khoản bị khóa'), ('force_logout', 'Admin cưỡng chế đăng xuất'), ('otp_fail', 'Xác thực OTP thất bại'), ('otp_success', 'Xác thực OTP thành công'), ('2fa_enable', 'Bật bảo mật 2FA'), ('2fa_disable', 'Tắt bảo mật 2FA'), ('register', 'Đăng ký tài khoản')], max_length=30, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp_code',
            field=models.CharField(max_length=6, verbose_name='Mã OTP (plaintext demo)'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Mã OTP SHA-256'),
        ),
        migrations.AlterField(
            model_name='remoteauthrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('approved', 'Đã đồng ý'), ('denied', 'Đã từ chối')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='User2FA',
        ),
        migrations.DeleteModel(
            name='UserSessionControl',
        ),
    ]
